[package]
name = "beats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
yew = { git = "https://github.com/yewstack/yew.git" }
log = "0.4.14"
wasm-logger = "0.2.0"
regex = "1.5.4"
wasm-bindgen = "0.2"
web-sys = "0.3"
js-sys = "0.3"
